# SEN66 Air Quality Sensor Configuration
# Hardware: Adafruit QT Py ESP32-S3 + Adafruit SEN66 breakout
# Connection: STEMMA QT cable
# Based on uELKO's ESPHome Air Quality Monitor

external_components:
  - source:
      type: git
      url: https://github.com/uELKO/esphome_external_components
      ref: rework
    components: sen6x

esp32:
  board: adafruit_qtpy_esp32s3_nopsram
  framework:
    type: esp-idf
    version: recommended

logger:

api:

ota:
  - platform: esphome

captive_portal:

web_server:
  port: 80
    auth:
    username: !secret web_username
    password: !secret web_password  # Optional - remove auth section for no password


i2c:
  sda: GPIO41  # QT Py STEMMA QT pins (NOT GPIO5/6!)
  scl: GPIO40
  scan: true
  id: bus_a

sensor:
  - platform: sen6x
    id: sen66
    pm_1_0:
      name: "PM1.0"
      id: sen66_pm10
      accuracy_decimals: 1
    pm_2_5:
      name: "PM2.5"
      id: sen66_pm25
      accuracy_decimals: 1
    pm_4_0:
      name: "PM4.0"
      id: sen66_pm40
      accuracy_decimals: 1
    pm_10_0:
      name: "PM10"
      id: sen66_pm100
      accuracy_decimals: 1
    co2:
      name: "CO2"
      id: sen66_co2
      accuracy_decimals: 0
    temperature:
      name: "Temperature"
      id: sen66_temp
      accuracy_decimals: 1
    humidity:
      name: "Humidity"
      id: sen66_humidity
      accuracy_decimals: 0
    voc:
      name: "VOC Index"
      id: sen66_voc
    nox:
      name: "NOx Index"
      id: sen66_nox
    store_baseline: true
    update_interval: 10s

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic

text_sensor:
  - platform: template
    name: "Air Quality Level"
    icon: "mdi:air-filter"
    lambda: |-
      if (id(sen66_pm25).state < 12.0) {
        return {"Good"};
      } else if (id(sen66_pm25).state < 35.4) {
        return {"Moderate"};
      } else if (id(sen66_pm25).state < 55.4) {
        return {"Unhealthy for Sensitive"};
      } else if (id(sen66_pm25).state < 150.4) {
        return {"Unhealthy"};
      } else {
        return {"Very Unhealthy"};
      }
    update_interval: 30s

  - platform: template
    name: "CO2 Level"
    icon: "mdi:molecule-co2"
    lambda: |-
      if (id(sen66_co2).state < 800) {
        return {"Excellent"};
      } else if (id(sen66_co2).state < 1000) {
        return {"Good"};
      } else if (id(sen66_co2).state < 1500) {
        return {"Moderate"};
      } else if (id(sen66_co2).state < 2000) {
        return {"Poor"};
      } else {
        return {"Very Poor"};
      }
    update_interval: 30s

  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic

button:
  - platform: restart
    name: "Restart"
    entity_category: diagnostic

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO39  # QT Py onboard NeoPixel
    num_leds: 1
    rmt_channel: 0
    chipset: WS2812
    name: "Status LED"
    id: status_led
    effects:
      - pulse:
          name: "Breathing"
          transition_length: 1s
          update_interval: 2s

interval:
  - interval: 30s
    then:
      - lambda: |-
          if (id(sen66_pm25).has_state()) {
            auto pm25 = id(sen66_pm25).state;
            auto call = id(status_led).turn_on();
            
            if (pm25 < 12.0) {
              call.set_rgb(0.0, 1.0, 0.0);  // Green - Good
            } else if (pm25 < 35.4) {
              call.set_rgb(1.0, 1.0, 0.0);  // Yellow - Moderate
            } else if (pm25 < 55.4) {
              call.set_rgb(1.0, 0.5, 0.0);  // Orange - Unhealthy for sensitive
            } else if (pm25 < 150.4) {
              call.set_rgb(1.0, 0.0, 0.0);  // Red - Unhealthy
            } else {
              call.set_rgb(0.5, 0.0, 0.5);  // Purple - Very unhealthy
            }
            call.set_brightness(0.2);
            call.set_effect("Breathing");
            call.perform();
          }